Traceback (most recent call last):
  File "/Users/eunhyechoe/anaconda3/envs/book/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/eunhyechoe/anaconda3/envs/book/lib/python3.9/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/eunhyechoe/anaconda3/envs/book/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/eunhyechoe/anaconda3/envs/book/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/eunhyechoe/anaconda3/envs/book/lib/python3.9/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/eunhyechoe/anaconda3/envs/book/lib/python3.9/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/eunhyechoe/anaconda3/envs/book/lib/python3.9/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
%%bash
pip install -U neuroboros
------------------

----- stderr -----
bash: /usr/local/bin/pip: /usr/local/opt/python@2/bin/python2.7: bad interpreter: No such file or directory
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mCalledProcessError[0m                        Traceback (most recent call last)
Cell [0;32mIn[1], line 1[0m
[0;32m----> 1[0m [43mget_ipython[49m[43m([49m[43m)[49m[38;5;241;43m.[39;49m[43mrun_cell_magic[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mbash[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mpip install -U neuroboros[39;49m[38;5;130;43;01m\n[39;49;00m[38;5;124;43m'[39;49m[43m)[49m

File [0;32m~/anaconda3/envs/book/lib/python3.9/site-packages/IPython/core/interactiveshell.py:2517[0m, in [0;36mInteractiveShell.run_cell_magic[0;34m(self, magic_name, line, cell)[0m
[1;32m   2515[0m [38;5;28;01mwith[39;00m [38;5;28mself[39m[38;5;241m.[39mbuiltin_trap:
[1;32m   2516[0m     args [38;5;241m=[39m (magic_arg_s, cell)
[0;32m-> 2517[0m     result [38;5;241m=[39m [43mfn[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m   2519[0m [38;5;66;03m# The code below prevents the output from being displayed[39;00m
[1;32m   2520[0m [38;5;66;03m# when using magics with decorator @output_can_be_silenced[39;00m
[1;32m   2521[0m [38;5;66;03m# when the last Python token in the expression is a ';'.[39;00m
[1;32m   2522[0m [38;5;28;01mif[39;00m [38;5;28mgetattr[39m(fn, magic[38;5;241m.[39mMAGIC_OUTPUT_CAN_BE_SILENCED, [38;5;28;01mFalse[39;00m):

File [0;32m~/anaconda3/envs/book/lib/python3.9/site-packages/IPython/core/magics/script.py:154[0m, in [0;36mScriptMagics._make_script_magic.<locals>.named_script_magic[0;34m(line, cell)[0m
[1;32m    152[0m [38;5;28;01melse[39;00m:
[1;32m    153[0m     line [38;5;241m=[39m script
[0;32m--> 154[0m [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mshebang[49m[43m([49m[43mline[49m[43m,[49m[43m [49m[43mcell[49m[43m)[49m

File [0;32m~/anaconda3/envs/book/lib/python3.9/site-packages/IPython/core/magics/script.py:314[0m, in [0;36mScriptMagics.shebang[0;34m(self, line, cell)[0m
[1;32m    309[0m [38;5;28;01mif[39;00m args[38;5;241m.[39mraise_error [38;5;129;01mand[39;00m p[38;5;241m.[39mreturncode [38;5;241m!=[39m [38;5;241m0[39m:
[1;32m    310[0m     [38;5;66;03m# If we get here and p.returncode is still None, we must have[39;00m
[1;32m    311[0m     [38;5;66;03m# killed it but not yet seen its return code. We don't wait for it,[39;00m
[1;32m    312[0m     [38;5;66;03m# in case it's stuck in uninterruptible sleep. -9 = SIGKILL[39;00m
[1;32m    313[0m     rc [38;5;241m=[39m p[38;5;241m.[39mreturncode [38;5;129;01mor[39;00m [38;5;241m-[39m[38;5;241m9[39m
[0;32m--> 314[0m     [38;5;28;01mraise[39;00m CalledProcessError(rc, cell)

[0;31mCalledProcessError[0m: Command 'b'pip install -U neuroboros\n'' returned non-zero exit status 126.

